CREATE TABLE game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE hand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    player_name VARCHAR(255),
    card_count INTEGER,
    game_id BIGINT,
    FOREIGN KEY (game_id) REFERENCES game(id)
);

CREATE TABLE hand_cards (
    hand_id BIGINT NOT NULL,
    card_type VARCHAR(255) NOT NULL,
    PRIMARY KEY (hand_id, card_type),
    FOREIGN KEY (hand_id) REFERENCES hand(id)
);

CREATE TABLE question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    card_type_shown VARCHAR(255),
    showing_card bit,
    game_id BIGINT,
    hand_id BIGINT,
    FOREIGN KEY (game_id) REFERENCES game(id),
    FOREIGN KEY (hand_id) REFERENCES hand(id)
);

CREATE TABLE question_card_types (
    question_id BIGINT NOT NULL,
    card_type VARCHAR(255) NOT NULL,
    PRIMARY KEY (question_id, card_type),
    FOREIGN KEY (question_id) REFERENCES question(id)
);